export default `
lung-cancer~Lung cancer~Ung thư phổi~oncology~Lung cancer|Ung thư phổi|bronchogenic carcinoma|ung thư phổi~persistent cough|weight loss|chest discomfort|coughing blood~large-volume hemoptysis|severe breathlessness|new neurologic deficit~smoking|radon|occupational exposure~copd|thrombosis|malnutrition~oncology plan|oxygenation|treatment toxicity|new symptoms
colorectal-cancer~Colorectal cancer~Ung thư đại trực tràng~oncology~Colorectal cancer|Ung thư đại trực tràng|colon cancer|rectal cancer|ung thư đại tràng~change in bowel habit|blood in stool|anemia|weight loss~bowel obstruction|heavy bleeding|severe abdominal pain~age|family history|polyps|inflammatory bowel disease~anemia|liver metastases|malnutrition~oncology plan|treatment toxicity|recurrence surveillance
prostate-cancer~Prostate cancer~Ung thư tuyến tiền liệt~oncology~Prostate cancer|Ung thư tuyến tiền liệt|prostate carcinoma|ung thư tiền liệt tuyến~often asymptomatic|urinary symptoms|bone pain in advanced disease~urinary retention|spinal cord compression symptoms|severe weakness~age|family history|genetic variants~bone disease|urinary obstruction|cardiovascular disease~oncology plan|urinary function|treatment toxicity
hiv~Human immunodeficiency virus infection~Nhiễm HIV~infectious~Human immunodeficiency virus infection|Nhiễm HIV|HIV infection|nhiễm HIV~may be asymptomatic|fever|weight loss|recurrent infections~severe breathlessness|neurologic symptoms|persistent high fever~blood exposure|sexual exposure|perinatal exposure~tuberculosis|hepatitis-b|kidney disease~viral load|CD4 when indicated|treatment adherence|drug interactions
dengue~Dengue~Sốt xuất huyết Dengue~infectious~Dengue|Sốt xuất huyết Dengue|dengue fever|sốt xuất huyết~fever|headache|muscle pain|rash~abdominal pain|persistent vomiting|bleeding|lethargy|breathing difficulty~mosquito exposure|endemic area|previous dengue infection~pregnancy|chronic disease|coagulopathy~hydration|warning signs|hematocrit and platelets when indicated
anemia~Anemia~Thiếu máu~hematology~Anemia|Thiếu máu|low hemoglobin|thiếu máu~fatigue|pallor|breathlessness|palpitations~chest pain|syncope|active bleeding|severe breathlessness~blood loss|nutritional deficiency|kidney disease|chronic inflammation~heart-failure|chronic-kidney-disease|cancer~hemoglobin|cause-specific tests|bleeding symptoms
venous-thromboembolism~Venous thromboembolism~Huyết khối tĩnh mạch~hematology~Venous thromboembolism|Huyết khối tĩnh mạch|VTE|deep vein thrombosis|pulmonary embolism|DVT|PE~unilateral leg swelling|leg pain|sudden breathlessness|pleuritic chest pain~sudden severe breathlessness|syncope|coughing blood|low oxygen~immobility|cancer|surgery|pregnancy~cancer|heart-failure|bleeding risk~symptoms|anticoagulant adherence|bleeding|kidney function
obesity~Obesity~Béo phì~metabolic~Obesity|Béo phì|adiposity|béo phì~may be asymptomatic|reduced exercise tolerance|sleep problems~severe breathlessness|chest pain|acute neurologic symptoms~genetic predisposition|dietary pattern|physical inactivity|medications~type-2-diabetes|hypertension|sleep apnea|fatty liver~weight trajectory|waist circumference|metabolic risk|sleep symptoms
obstructive-sleep-apnea~Obstructive sleep apnea~Ngưng thở khi ngủ do tắc nghẽn~respiratory~Obstructive sleep apnea|Ngưng thở khi ngủ do tắc nghẽn|OSA|sleep apnea|ngưng thở khi ngủ~loud snoring|witnessed apneas|daytime sleepiness|morning headache~drowsy driving|severe hypoxemia|cardiorespiratory instability~obesity|craniofacial anatomy|age~hypertension|atrial-fibrillation|type-2-diabetes~sleepiness|device adherence when prescribed|blood pressure
pregnancy-hypertension~Hypertensive disorders of pregnancy~Rối loạn tăng huyết áp thai kỳ~obstetric~Hypertensive disorders of pregnancy|Rối loạn tăng huyết áp thai kỳ|preeclampsia|tiền sản giật|tăng huyết áp thai kỳ~high blood pressure|headache|visual change|upper abdominal pain~seizure|severe headache|vision loss|heavy bleeding|reduced fetal movement~first pregnancy|multiple gestation|chronic hypertension|kidney disease~gestational diabetes|kidney disease|fetal growth restriction~blood pressure|urine protein|maternal symptoms|fetal assessment
gestational-diabetes~Gestational diabetes~Đái tháo đường thai kỳ~obstetric~Gestational diabetes|Đái tháo đường thai kỳ|GDM|tiểu đường thai kỳ~often asymptomatic|increased thirst|frequent urination~vomiting|confusion|markedly high glucose with illness~obesity|family history|previous gestational diabetes~pregnancy-hypertension|large-for-gestational-age fetus~glucose|fetal growth|postpartum diabetes screening
atopic-dermatitis~Atopic dermatitis~Viêm da cơ địa~dermatology~Atopic dermatitis|Viêm da cơ địa|eczema|chàm|viêm da cơ địa~itchy inflamed skin|dryness|recurrent flares~rapidly spreading painful rash|fever|eye involvement~family history|allergy|skin barrier dysfunction~asthma|allergic rhinitis|sleep disturbance~flare frequency|infection signs|sleep|treatment adverse effects
psoriasis~Psoriasis~Vảy nến~dermatology~Psoriasis|Vảy nến|plaque psoriasis|vảy nến~well-demarcated plaques|scaling|itching~widespread redness|fever|severe joint symptoms~family history|smoking|obesity~psoriatic arthritis|cardiovascular disease|depression~skin extent|joint symptoms|metabolic risk|treatment toxicity
`.trim();
