export default `
hypertension~Hypertension~Tăng huyết áp~cardiovascular~Hypertension|Tăng huyết áp|high blood pressure|cao huyết áp~often asymptomatic|headache|dizziness~chest pain|neurologic deficit|severe breathlessness~age|obesity|high sodium intake|kidney disease~type-2-diabetes|chronic-kidney-disease|heart-failure|stroke~blood pressure trend|kidney function|electrolytes
coronary-artery-disease~Coronary artery disease~Bệnh động mạch vành~cardiovascular~Coronary artery disease|Bệnh động mạch vành|ischemic heart disease|bệnh mạch vành~exertional chest discomfort|shortness of breath|fatigue~persistent chest pressure|sweating|fainting~smoking|diabetes|hypertension|dyslipidemia~heart-failure|chronic-kidney-disease~symptom pattern|lipids|blood pressure
heart-failure~Heart failure~Suy tim~cardiovascular~Heart failure|Suy tim|congestive heart failure|CHF|suy tim sung huyết~breathlessness|leg swelling|orthopnea|fatigue~breathlessness at rest|blue lips|confusion|rapid worsening edema~coronary disease|hypertension|cardiomyopathy~chronic-kidney-disease|atrial-fibrillation|type-2-diabetes|copd~daily weight|symptoms|kidney function|electrolytes
atrial-fibrillation~Atrial fibrillation~Rung nhĩ~cardiovascular~Atrial fibrillation|Rung nhĩ|AF|AFib~palpitations|fatigue|breathlessness|dizziness~syncope|chest pain|stroke symptoms~age|hypertension|heart disease|thyroid disease~heart-failure|stroke|chronic-kidney-disease~heart rate|rhythm|bleeding risk when anticoagulated
stroke~Stroke~Đột quỵ~neurology~Stroke|Đột quỵ|cerebrovascular accident|CVA|tai biến mạch máu não~face droop|arm weakness|speech difficulty|sudden imbalance~any sudden focal neurologic deficit~hypertension|atrial fibrillation|diabetes|smoking~dysphagia|mobility impairment|depression~neurologic recovery|swallowing|blood pressure
type-1-diabetes~Type 1 diabetes mellitus~Đái tháo đường type 1~endocrine~Type 1 diabetes mellitus|Đái tháo đường type 1|T1DM|tiểu đường type 1~thirst|frequent urination|weight loss|fatigue~vomiting|deep breathing|confusion|ketones~autoimmune predisposition|family history~thyroid disease|celiac disease|kidney disease~glucose|ketones when unwell|HbA1c|kidney and eye screening
type-2-diabetes~Type 2 diabetes mellitus~Đái tháo đường type 2~endocrine~Type 2 diabetes mellitus|Đái tháo đường type 2|T2DM|tiểu đường type 2|đái tháo đường|tiểu đường~thirst|frequent urination|fatigue|slow wound healing~altered consciousness|severe dehydration|very high glucose with illness~obesity|family history|age|gestational diabetes~hypertension|chronic-kidney-disease|fatty liver|cardiovascular disease~glucose|HbA1c|kidney function|eyes|feet
hypothyroidism~Hypothyroidism~Suy giáp~endocrine~Hypothyroidism|Suy giáp|underactive thyroid|suy tuyến giáp~fatigue|cold intolerance|constipation|weight gain~severe drowsiness|hypothermia|slow breathing~autoimmune thyroiditis|thyroid surgery~dyslipidemia|depression|cardiovascular disease~TSH|free T4|symptoms
hyperthyroidism~Hyperthyroidism~Cường giáp~endocrine~Hyperthyroidism|Cường giáp|overactive thyroid|cường tuyến giáp~palpitations|heat intolerance|weight loss|tremor~fever|agitation|very fast heart rate|heart failure symptoms~Graves disease|thyroid nodules~atrial-fibrillation|osteoporosis|heart-failure~TSH|free T4/T3|heart rate
chronic-kidney-disease~Chronic kidney disease~Bệnh thận mạn~renal~Chronic kidney disease|Bệnh thận mạn|CKD|suy thận mạn|bệnh thận mạn~often asymptomatic|fatigue|swelling|itching~breathlessness|confusion|very low urine output|severe weakness~diabetes|hypertension|glomerular disease~heart-failure|anemia|mineral bone disorder|hyperkalemia~eGFR|urine albumin|potassium|hemoglobin|blood pressure
acute-kidney-injury~Acute kidney injury~Tổn thương thận cấp~renal~Acute kidney injury|Tổn thương thận cấp|AKI|suy thận cấp~reduced urine|nausea|swelling|fatigue~no urine|breathlessness|confusion|arrhythmia symptoms~dehydration|sepsis|nephrotoxic medicines|obstruction~chronic-kidney-disease|heart-failure|liver disease~urine output|creatinine|potassium|fluid balance
asthma~Asthma~Hen phế quản~respiratory~Asthma|Hen phế quản|bronchial asthma|hen suyễn~wheeze|cough|chest tightness|variable breathlessness~unable to speak full sentences|blue lips|silent chest|exhaustion~allergy|family history|smoke exposure~rhinitis|eczema|obesity|anxiety~symptom control|reliever use|peak flow when advised|inhaler technique
copd~Chronic obstructive pulmonary disease~Bệnh phổi tắc nghẽn mạn tính~respiratory~Chronic obstructive pulmonary disease|Bệnh phổi tắc nghẽn mạn tính|COPD|chronic bronchitis|emphysema|BPTNMT~chronic cough|sputum|progressive breathlessness~severe breathlessness|blue lips|drowsiness|new confusion~smoking|biomass exposure|occupational exposure~heart disease|osteoporosis|anxiety|lung cancer~exacerbations|oxygen saturation when indicated|spirometry|weight
pneumonia~Pneumonia~Viêm phổi~infectious~Pneumonia|Viêm phổi|lung infection~fever|cough|sputum|breathlessness~low oxygen|confusion|severe breathlessness|persistent chest pain~age extremes|chronic lung disease|immunosuppression~sepsis|copd|heart-failure~temperature|breathing|oxygenation|hydration
tuberculosis~Tuberculosis~Lao~infectious~Tuberculosis|Lao|TB|pulmonary tuberculosis|bệnh lao~prolonged cough|weight loss|night sweats|fever~coughing blood|severe breathlessness|neurologic symptoms~close exposure|immunosuppression|crowded living conditions~HIV|type-2-diabetes|malnutrition~treatment adherence|liver toxicity symptoms|microbiologic follow-up
`.trim();
