export default `
hepatitis-b~Chronic hepatitis B~Viêm gan B mạn~hepatic~Chronic hepatitis B|Viêm gan B mạn|HBV|viêm gan siêu vi B~often asymptomatic|fatigue|right upper abdominal discomfort~jaundice with confusion|vomiting blood|marked abdominal swelling~perinatal exposure|blood exposure|sexual exposure~cirrhosis|liver cancer|kidney disease~ALT|HBV DNA when indicated|fibrosis assessment|liver cancer surveillance
cirrhosis~Cirrhosis~Xơ gan~hepatic~Cirrhosis|Xơ gan|liver cirrhosis~fatigue|jaundice|abdominal swelling|easy bruising~vomiting blood|black stools|confusion|fever with ascites~viral hepatitis|alcohol|metabolic fatty liver~kidney dysfunction|malnutrition|liver cancer~weight and ascites|mental status|liver and kidney tests|cancer surveillance
metabolic-fatty-liver~Metabolic dysfunction-associated steatotic liver disease~Bệnh gan nhiễm mỡ liên quan chuyển hóa~hepatic~Metabolic dysfunction-associated steatotic liver disease|Bệnh gan nhiễm mỡ liên quan chuyển hóa|MASLD|NAFLD|fatty liver|gan nhiễm mỡ~often asymptomatic|fatigue|right upper abdominal discomfort~jaundice|abdominal swelling|confusion~obesity|diabetes|dyslipidemia~cardiovascular disease|sleep apnea|chronic-kidney-disease~weight|metabolic risk|liver enzymes|fibrosis risk
gerd~Gastroesophageal reflux disease~Trào ngược dạ dày thực quản~gastrointestinal~Gastroesophageal reflux disease|Trào ngược dạ dày thực quản|GERD|acid reflux|trào ngược~heartburn|regurgitation|chronic cough~difficulty swallowing|vomiting blood|black stools|unintentional weight loss~obesity|pregnancy|hiatal hernia~asthma|sleep disturbance|esophagitis~alarm symptoms|response to treatment|weight
inflammatory-bowel-disease~Inflammatory bowel disease~Bệnh viêm ruột~gastrointestinal~Inflammatory bowel disease|Bệnh viêm ruột|IBD|Crohn disease|ulcerative colitis|viêm ruột~diarrhea|abdominal pain|blood in stool|weight loss~severe abdominal distension|heavy bleeding|dehydration|high fever~family history|immune dysregulation|smoking pattern~anemia|arthritis|liver disease|thrombosis~stool frequency|weight|blood count|inflammation markers
migraine~Migraine~Đau nửa đầu~neurology~Migraine|Đau nửa đầu|migraine headache|đau đầu migraine~recurrent headache|nausea|light sensitivity|aura~sudden worst headache|new neurologic deficit|fever with stiff neck~family history|hormonal factors|sleep disruption~anxiety|depression|sleep disorder~attack frequency|disability|medication overuse
epilepsy~Epilepsy~Động kinh~neurology~Epilepsy|Động kinh|seizure disorder|động kinh~recurrent unprovoked seizures|brief altered awareness|convulsions~seizure lasting more than five minutes|repeated seizures without recovery|injury|pregnancy~brain injury|stroke|genetic factors~depression|cognitive impairment|sleep disorder~seizure frequency|medicine adherence|adverse effects
parkinson-disease~Parkinson disease~Bệnh Parkinson~neurology~Parkinson disease|Bệnh Parkinson|Parkinsonism|Parkinson~slowness|tremor|rigidity|balance problems~sudden marked decline|aspiration|severe confusion~age|family history|environmental exposure~depression|constipation|sleep disorder|dementia~mobility|falls|swallowing|cognition
depression~Major depressive disorder~Trầm cảm~mental-health~Major depressive disorder|Trầm cảm|depression|rối loạn trầm cảm~persistent low mood|loss of interest|sleep change|hopelessness~suicidal thoughts|psychosis|inability to care for self~family history|trauma|chronic illness~anxiety|substance use|chronic pain~suicide risk|function|sleep|treatment response
generalized-anxiety~Generalized anxiety disorder~Rối loạn lo âu lan tỏa~mental-health~Generalized anxiety disorder|Rối loạn lo âu lan tỏa|GAD|lo âu~excessive worry|restlessness|muscle tension|poor sleep~suicidal thoughts|severe panic with medical symptoms|substance withdrawal~family history|stress|chronic illness~depression|insomnia|substance use~worry severity|function|sleep|treatment response
bipolar-disorder~Bipolar disorder~Rối loạn lưỡng cực~mental-health~Bipolar disorder|Rối loạn lưỡng cực|bipolar affective disorder|lưỡng cực~episodes of elevated mood|reduced sleep need|depression|impulsivity~suicidal thoughts|psychosis|dangerous behavior|severe agitation~family history|sleep disruption|substance exposure~anxiety|substance use|metabolic disease~mood episodes|sleep|medicine safety|metabolic parameters
osteoarthritis~Osteoarthritis~Thoái hóa khớp~musculoskeletal~Osteoarthritis|Thoái hóa khớp|OA|thoái hóa khớp~activity-related joint pain|brief stiffness|reduced mobility~hot swollen joint|fever|major trauma~age|obesity|joint injury~obesity|cardiovascular disease|depression~pain|function|mobility|medicine harms
rheumatoid-arthritis~Rheumatoid arthritis~Viêm khớp dạng thấp~autoimmune~Rheumatoid arthritis|Viêm khớp dạng thấp|RA|viêm đa khớp dạng thấp~symmetric joint swelling|prolonged morning stiffness|fatigue~fever with immunosuppression|new neurologic symptoms|severe breathing symptoms~smoking|family history|female sex~cardiovascular disease|lung disease|osteoporosis~joint activity|blood counts|liver tests|infection risk
systemic-lupus~Systemic lupus erythematosus~Lupus ban đỏ hệ thống~autoimmune~Systemic lupus erythematosus|Lupus ban đỏ hệ thống|SLE|lupus~fatigue|joint pain|rash|photosensitivity~chest pain|neurologic symptoms|reduced urine|pregnancy complications~female sex|family history|autoimmune predisposition~kidney disease|thrombosis|cardiovascular disease~urine|kidney function|blood counts|disease activity
breast-cancer~Breast cancer~Ung thư vú~oncology~Breast cancer|Ung thư vú|carcinoma of breast|ung thư vú~breast lump|skin or nipple change|unilateral discharge~rapidly progressive swelling|severe breathlessness|neurologic deficit~age|family history|genetic variants|hormonal exposure~lymphedema|bone disease|cardiovascular toxicity~oncology plan|treatment toxicity|recurrence symptoms
`.trim();
